#!/bin/bash

export DELETED=$'\e[38;5;252;48;5;52m' ; export DIFF=$'\e[38;5;252;48;5;25m'; export ONLY=$'\e[38;5;252;48;5;28m'
export do_diff=1
export TDD 
interactive=1

# Parse options
[[ "$1" ]]  || { echo "paneless: need at least one input" ; exit 1 ; }

options=$(getopt -o g,h,m:,M -l help,mode: -n "$0" -- "$@") || exit
eval set -- "$options"

while [[ $1 != -- ]]; do
	case $1 in
		-m|--mode       ) mode=$1                       ; shift 2 ;;
		-g              ) show_manifest=1 interactive=0 ; shift   ;;
		-M              ) show_manifest=1               ; shift   ;;
		-h|--help       )
				echo "NAME"
				echo "    tdiff - tree diff visualization"
				echo
				echo "SYNOPSIS"
				echo "    tdiff dir dir"
				echo "    tdiff file <(...)"
				echo
				echo "OPTIONS"
				echo "    --mode       all|common|diff|all_d2_only"
				echo "    -g           only generate manifest"
				echo "    -M           display manifest location"
				exit ;;
		*               ) echo "tdiff: bad option: $1" >&2; exit 1;;
	esac
done

shift # -- in argument list to getopt

[[ "$1" != "$2" ]] || { echo tdiff: comparing to oneself ; exit 1 ; }

{ [[ -d "$1" && -d "$2" ]] ||  [[ -f "$1" && -f "$2" ]] ; } ||
	{ echo tdiff: entries to compare are not of the same type ; exit 1 ; }

: ${mode:=all} 
[[ "$mode" == all || "$mode" == common || "$mode" = diff || "$mode" == all_d2_only ]] ||
	{ echo "tdiff: valid modes: all|common|diff|all_d2_only" ; exit 1 ; }

{ read tree1 ; read tree2 ; read manifest ; } < <($(dirname $0)/tree_synch "$1" "$2" "$mode") || exit

(( interactive ))   && paneless -a --no-color -c $(dirname $0)/tdiff.pless --status-line -E "$manifest" $tree1 $tree2 
(( show_manifest )) && echo "tdiff: manifest: $manifest" 

# vim: set ft=bash:
